--- 
before_install: 
  - "rm -rf ~/.gvm"
  - "curl -s get.gvmtool.net > ~/install_gvm.sh"
  - "chmod 775 ~/install_gvm.sh"
  - ~/install_gvm.sh
  - "echo \"gvm_auto_answer=true\" > ~/.gvm/etc/config"
  - "source ~/.gvm/bin/gvm-init.sh"
  - "gvm install grails $GRAILS_VERSION || true"
env: 
  - GRAILS_VERSION=2.0.4
  - GRAILS_VERSION=2.2.5
  - GRAILS_VERSION=2.3.11
language: groovy
jdk:
 - openjdk7
 - openjdk8
sudo: false
script:
  - grails clean
  - case $GRAILS_VERSION in
      2.4* ) grails set-grails-version $GRAILS_VERSION ;;
      2.5* ) grails set-grails-version $GRAILS_VERSION ;;
      * ) grails upgrade --non-interactive ;;
    esac
  - grails test-app --non-interactive --stacktrace
