--- 
before_install: 
  - "rm -rf ~/.gvm"
  - "curl -s get.gvmtool.net > ~/install_gvm.sh"
  - "chmod 775 ~/install_gvm.sh"
  - ~/install_gvm.sh
  - "echo \"gvm_auto_answer=true\" > ~/.gvm/etc/config"
  - "source ~/.gvm/bin/gvm-init.sh"
  - "gvm install grails $GRAILS_VERSION || true"
env: 
  - GRAILS_VERSION=2.0.4
  - GRAILS_VERSION=2.3.4
language: groovy
script: "grails  test-app --non-interactive"
